### PR TITLE
Sort coach list by school, added missing details and delete actions.

### PR DESCRIPTION
**Pull request by vperez-rwserver**

### CODE REVIEW

**Comment by vperez-rwserver** [comment]
[Swimmers and Coaches should be able to sign up easily.](https://trello.com/c/ic2mpvlB/39-swimmers-and-coaches-should-be-able-to-sign-up-easily)

**Comment by dawoodman71** [comment]
I registered as a coach in IE and then went to the verify screen in Chrome. When I tried to delete the new entry I go the same error as above.

**Comment by vperez-rwserver** [comment]
looking into it

**Comment by vperez-rwserver** [comment]
Fix for this has been pushed. Please let me know any issues.

**Comment by dawoodman71** [comment]
I got a different error this time. Looks like there may be some differences between our local databases.

image

**Comment by dawoodman71** [comment]
I think this is due to my tampering with the UsersInRoles table when I made myself the admin/coach/swimmer.  The fresh coach I added deleted fine.

I don't think this is an issue since no one will be manually updating the database (or shouldn't be).

**Comment by vperez-rwserver** [comment]
Possibly, I set it up to only remove Coach role. 

This is an edge case that I think would be unlikely to happen  in production since unverified coaches should never have more than the Coach role. 

Maybe doing a check before deleting and disabling delete option if the account has more than just the Coach role?

**Pull request merged**
