### PR TITLE
Working swimmer search for coaches

### PR DESCRIPTION
**Pull request by vperez-rwserver**

### CODE REVIEW

**Comment by vperez-rwserver** [comment]
[Coaches use filters to search for specific swimmers which makes finding their dream team easier.](https://trello.com/c/5U2pn1D5/4-coaches-use-filters-to-search-for-specific-swimmers-which-makes-finding-their-dream-team-easier)

**Comment by dawoodman71** [comment]
When I try to view this branch locally the web.config reverts to the old one and I get errors. Not sure why this is because web.config wasn't changed in this branch. Sometimes git breaks my brain.

**Comment by dawoodman71** [comment]
I can't get this page to work. I added a record in Coaches with my info, updated my record in UserProfiles with the new CoachId and added a record in UsersInRoles to put me in the Coach Role.

This got me into the coaches area, but when I try to do a search I get a nullPointerException.

**Comment by dawoodman71** [comment]
I placed some breakpoints and debugged the CoachSwimmerSearch branch.

First it shows an Exception where CoachSwimmerSearch is instantiated:
image

I'm sure this is an easy fix. I might have missed something in my Coach setup. We'll touch on this in the morning. Have a great rest of your weekend.

**Comment by dawoodman71** [comment]
Got it working - issue was with incorrect school id in Coach record.

**Pull request merged**
